// <auto-generated />
namespace ClassLibrary1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Dress_BoughtDate_ToNullAble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dress_BoughtDate_ToNullAble));
        
        string IMigrationMetadata.Id
        {
            get { return "201910180935253_Dress_BoughtDate_ToNullAble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
